### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by kenoyer**

### CODE REVIEW

**Comment by commadelimited** [comment]
@kenoyer, this would be changing the default theme for everyone.

**Comment by kenoyer** [comment]
I;m so sorry about that.

Date: Tue, 22 Jul 2014 19:06:04 -0700

**Comment by commadelimited** [comment]
No worries. Thanks for checking out the theme though. Hope you like it.

**Comment by kenoyer** [comment]
Save my butt on a demo presentation I had to do in a few hours.

Thanks for the share. Maybe we can relate more directly...who know we may be somewhat mutually beneficial.

Kenoye R.
Kenoyelive@live.com

--- Original Message ---

**Pull request closed without merging**
